#include <lv2/macros.h.S>
#include <lv2/symbols.h>

#ifdef sys_net_bnet_bind_symbol
LV2_FUNCTION(sys_net_bnet_bind, sys_net_bnet_bind_symbol)
#endif

#ifdef sys_net_bnet_close_symbol
LV2_FUNCTION(sys_net_bnet_close, sys_net_bnet_close_symbol)
#endif

#ifdef sys_net_bnet_connect_symbol
LV2_FUNCTION(sys_net_bnet_connect, sys_net_bnet_connect_symbol)
#endif

#ifdef sys_net_bnet_poll_symbol
LV2_FUNCTION(sys_net_bnet_poll, sys_net_bnet_poll_symbol)
#endif

#ifdef sys_net_bnet_sendto_symbol
LV2_FUNCTION(sys_net_bnet_sendto, sys_net_bnet_sendto_symbol)
#endif

#ifdef sys_net_bnet_setsockopt_symbol
LV2_FUNCTION(sys_net_bnet_setsockopt, sys_net_bnet_setsockopt_symbol)
#endif

#ifdef sys_net_bnet_shutdown_symbol
LV2_FUNCTION(sys_net_bnet_shutdown, sys_net_bnet_shutdown_symbol)
#endif

#ifdef sys_net_bnet_socket_symbol
LV2_FUNCTION(sys_net_bnet_socket, sys_net_bnet_socket_symbol)
#endif
